version: "3.7"
services:
  db:
    image: postgres:16
    container_name: app_db
    environment:
      POSTGRES_PASSWORD: Reubjeon512
      POSTGRES_DB: fastapi
    command: ["postgres", "-p", "5432", "-c", "max_connections=300"]
    ports:
      - 5432
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: trello_app
    command: ["app.sh"]
    ports:
      - 9191:8000
    depends_on:
      - db

