"""Initial

Revision ID: 0222fb52b50b
Revises: 88966566775b
Create Date: 2023-12-11 17:41:07.773767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0222fb52b50b'
down_revision: Union[str, None] = '88966566775b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('allowed_user_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'allowed_user_ids')
    # ### end Alembic commands ###
