"""Initial

Revision ID: 16968de8ebbe
Revises: 24d7de22805d
Create Date: 2023-12-11 15:27:33.080858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16968de8ebbe'
down_revision: Union[str, None] = '24d7de22805d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'parent_task_id')
    # ### end Alembic commands ###
