"""Initial

Revision ID: 24d7de22805d
Revises: 84c05025a98c
Create Date: 2023-12-10 21:58:32.904569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d7de22805d'
down_revision: Union[str, None] = '84c05025a98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'task', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'board_id')
    op.drop_column('task', 'status_id')
    op.drop_table('status')
    op.drop_table('board')
    # ### end Alembic commands ###
