"""Initial

Revision ID: 7425d18df70f
Revises: 7f5aaaff1a6d
Create Date: 2023-12-11 20:33:11.619135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7425d18df70f'
down_revision: Union[str, None] = '7f5aaaff1a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('logger_log_id_user_fkey', 'logger', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('logger_log_id_user_fkey', 'logger', 'user', ['log_id_user'], ['id'])
    # ### end Alembic commands ###
