"""Initial

Revision ID: 7f5aaaff1a6d
Revises: 6adf7e85633d
Create Date: 2023-12-11 20:26:08.248185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5aaaff1a6d'
down_revision: Union[str, None] = '6adf7e85633d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('logger_log_email_user_fkey', 'logger', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('logger_log_email_user_fkey', 'logger', 'user', ['log_email_user'], ['email'])
    # ### end Alembic commands ###
