"""Initial

Revision ID: 88966566775b
Revises: 16968de8ebbe
Create Date: 2023-12-11 16:01:15.065477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88966566775b'
down_revision: Union[str, None] = '16968de8ebbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('allowed_to_visible_user_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'allowed_to_visible_user_ids')
    # ### end Alembic commands ###
