"""Initial

Revision ID: aacfe1f6c7cf
Revises: 71dc33fb4c06
Create Date: 2023-12-09 03:01:32.658645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacfe1f6c7cf'
down_revision: Union[str, None] = '71dc33fb4c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logger', sa.Column('log_name_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logger', 'log_name_user')
    # ### end Alembic commands ###
