"""Initial

Revision ID: d7af94c50ad8
Revises: 0222fb52b50b
Create Date: 2023-12-11 19:40:57.859769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7af94c50ad8'
down_revision: Union[str, None] = '0222fb52b50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('text_content', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('task', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('task', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('task', sa.Column('image_content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'image_content')
    op.drop_column('task', 'audio_url')
    op.drop_column('task', 'video_url')
    op.drop_column('task', 'image_url')
    op.drop_column('task', 'text_content')
    # ### end Alembic commands ###
